"""
This family file was auto-generated by generate_family_file.py script.

Configuration parameters:
  url = https://zh.postal.wiki/api.php
  name = zhpw

Please do not commit this to the Git repository!
"""
from pywikibot import family


class Family(family.Family):  # noqa: D101

    name = 'zhpw'
    langs = {
        'zh': 'zh.postal.wiki',
    }

    def scriptpath(self, code):
        return {
            'zh': '',
        }[code]

    def protocol(self, code):
        return {
            'zh': 'https',
        }[code]
